name: map_mvp_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  freezed_annotation: ^2.4.4
  dio: ^5.0.0
  logger: ^2.4.0  # Update to the latest version

  # Map rendering and GeoJSON handling
  flutter_map: ^7.0.2
  flutter_map_geojson: ^1.0.8  
  latlong2: ^0.9.0

  # Use upgradable or resolvable versions for stability
  collection: ^1.18.0  # Upgradable
  http_parser: ^4.0.2  # Upgradable
  material_color_utilities: ^0.11.1  # Upgradable
  meta: ^1.15.0  # Upgradable
  string_scanner: ^1.2.0  # Upgradable

  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.0.0       
  freezed: ^2.5.7            
  flutter_test:
    sdk: flutter             
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/map_core/maps/country_continents.geojson  
    - lib/map_core/maps/Earth1_Pseudo_Marcader_png.png